spring:
  application:
    name: bank-backend
  datasource:
    password: password
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: create
    show-sql: true
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
